CREATE TABLE lessons (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  title VARCHAR2(255) NOT NULL,
  content VARCHAR2(1000) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO lessons (title, content) VALUES ('Introduction to JavaScript', 'JavaScript is a programming language...');
INSERT INTO lessons (title, content) VALUES ('HTML Basics', 'HTML (Hypertext Markup Language) is...');
INSERT INTO lessons (title, content) VALUES ('CSS Styling', 'CSS (Cascading Style Sheets) is...');

